### ISSUE TITLE
Final To-Do List

### ISSUE THREAD

**Issue by vidia** [dschrag/DefinitelyNotDontStarve#32]
- [x] Eat Food

- [x] Die
- [x] Kill Rat, Place Carcas
- [x] Make items lay on ground
- [x] Bat 
- [ ] Fade

- [ ] Rat Animation

- [x] Mesh

- [x] Remove debug

### Sounds 

- [x] Food
- [x] Stomach

- [x] Heart

- [x] Wind

- [x] Breathing

- [x] Bat, Rat

- [x] Breaking Wood (For the crate)

- [x] Ambient Music (Minecraft?)
